namespace ASiNet.CustomTelegramBot.Enums;
[Flags]
public enum MessageTypeFlags : long
{
    None = 0,
    Text = 1L << 0,
    Photo = 1L << 1,
    Audio = 1L << 2,
    Video = 1L << 3,
    Voice = 1L << 4,
    Document = 1L << 5,
    Sticker = 1L << 6,
    Location = 1L << 7,
    Contact = 1L << 8,
    Venue = 1L << 9,
    Game = 1L << 10,
    VideoNote = 1L << 11,
    Invoice = 1L << 12,
    SuccessfulPayment = 1L << 13,
    WebsiteConnected = 1L << 14,
    ChatMembersAdded = 1L << 15,
    ChatMemberLeft = 1L << 16,
    ChatTitleChanged = 1L << 17,
    ChatPhotoChanged = 1L << 18,
    MessagePinned = 1L << 19,
    ChatPhotoDeleted = 1L << 20,
    GroupCreated = 1L << 21,
    SupergroupCreated = 1L << 22,
    ChannelCreated = 1L << 23,
    MigratedToSupergroup = 1L << 24,
    MigratedFromGroup = 1L << 25,
    Poll = 1L << 26,
    Dice = 1L << 27,
    MessageAutoDeleteTimerChanged = 1L << 28,
    ProximityAlertTriggered = 1L << 29,
    WebAppData = 1L << 30,
    VideoChatScheduled = 1L << 31,
    VideoChatStarted = 1L << 32,
    VideoChatEnded = 1L << 33,
    VideoChatParticipantsInvited = 1L << 34,
    Animation = 1L << 35,
    ForumTopicCreated = 1L << 36,
    ForumTopicClosed = 1L << 37,
    ForumTopicReopened = 1L << 38,
    ForumTopicEdited = 1L << 39,
    GeneralForumTopicHidden = 1L << 40,
    GeneralForumTopicUnhidden = 1L << 41,
    WriteAccessAllowed = 1L << 42,
    AllTypes = 43,
}